# Generated by Django 4.0.4 on 2022-05-19 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='comment_author', max_length=50, verbose_name='isim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(default='comment_content', max_length=200, verbose_name='Yorum'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
