# Generated by Django 4.0.4 on 2022-05-19 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment_comment_author_comment_comment_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
    ]
