# Generated by Django 4.0.4 on 2022-05-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='default value', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='default name', max_length=50, verbose_name='İsim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='default surname', max_length=50, verbose_name='Soyisim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='user_image',
            field=models.FileField(default='default pic', upload_to=''),
            preserve_default=False,
        ),
    ]
